# Generated by Django 3.2.4 on 2022-01-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20220113_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='IMGURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
